// flow-typed signature: f5fbc28664779f1f5de21d43c0568a81
// flow-typed version: <<STUB>>/inspect-process_v^0.5.0/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'inspect-process'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'inspect-process' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'inspect-process/bin/inspect' {
  declare module.exports: any;
}

declare module 'inspect-process/lib/devtools' {
  declare module.exports: any;
}

declare module 'inspect-process/lib/index' {
  declare module.exports: any;
}

declare module 'inspect-process/test/fixtures/required' {
  declare module.exports: any;
}

declare module 'inspect-process/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'inspect-process/bin/inspect.js' {
  declare module.exports: $Exports<'inspect-process/bin/inspect'>;
}
declare module 'inspect-process/lib/devtools.js' {
  declare module.exports: $Exports<'inspect-process/lib/devtools'>;
}
declare module 'inspect-process/lib/index.js' {
  declare module.exports: $Exports<'inspect-process/lib/index'>;
}
declare module 'inspect-process/test/fixtures/required.js' {
  declare module.exports: $Exports<'inspect-process/test/fixtures/required'>;
}
declare module 'inspect-process/test/index.js' {
  declare module.exports: $Exports<'inspect-process/test/index'>;
}
