// flow-typed signature: 139c3df146e09867a5cd932c8640ce53
// flow-typed version: <<STUB>>/vuenit_v^1.0.0/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vuenit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vuenit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vuenit/lib/cleanUp' {
  declare module.exports: any;
}

declare module 'vuenit/lib/component/augment' {
  declare module.exports: any;
}

declare module 'vuenit/lib/component/build' {
  declare module.exports: any;
}

declare module 'vuenit/lib/component/component' {
  declare module.exports: any;
}

declare module 'vuenit/lib/component/expose-array' {
  declare module.exports: any;
}

declare module 'vuenit/lib/component/index' {
  declare module.exports: any;
}

declare module 'vuenit/lib/component/injectors' {
  declare module.exports: any;
}

declare module 'vuenit/lib/component/options' {
  declare module.exports: any;
}

declare module 'vuenit/lib/directive' {
  declare module.exports: any;
}

declare module 'vuenit/lib/helpers' {
  declare module.exports: any;
}

declare module 'vuenit/lib/index' {
  declare module.exports: any;
}

declare module 'vuenit/lib/reactify' {
  declare module.exports: any;
}

declare module 'vuenit/lib/trigger' {
  declare module.exports: any;
}

declare module 'vuenit/lib/vue' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vuenit/lib/cleanUp.js' {
  declare module.exports: $Exports<'vuenit/lib/cleanUp'>;
}
declare module 'vuenit/lib/component/augment.js' {
  declare module.exports: $Exports<'vuenit/lib/component/augment'>;
}
declare module 'vuenit/lib/component/build.js' {
  declare module.exports: $Exports<'vuenit/lib/component/build'>;
}
declare module 'vuenit/lib/component/component.js' {
  declare module.exports: $Exports<'vuenit/lib/component/component'>;
}
declare module 'vuenit/lib/component/expose-array.js' {
  declare module.exports: $Exports<'vuenit/lib/component/expose-array'>;
}
declare module 'vuenit/lib/component/index.js' {
  declare module.exports: $Exports<'vuenit/lib/component/index'>;
}
declare module 'vuenit/lib/component/injectors.js' {
  declare module.exports: $Exports<'vuenit/lib/component/injectors'>;
}
declare module 'vuenit/lib/component/options.js' {
  declare module.exports: $Exports<'vuenit/lib/component/options'>;
}
declare module 'vuenit/lib/directive.js' {
  declare module.exports: $Exports<'vuenit/lib/directive'>;
}
declare module 'vuenit/lib/helpers.js' {
  declare module.exports: $Exports<'vuenit/lib/helpers'>;
}
declare module 'vuenit/lib/index.js' {
  declare module.exports: $Exports<'vuenit/lib/index'>;
}
declare module 'vuenit/lib/reactify.js' {
  declare module.exports: $Exports<'vuenit/lib/reactify'>;
}
declare module 'vuenit/lib/trigger.js' {
  declare module.exports: $Exports<'vuenit/lib/trigger'>;
}
declare module 'vuenit/lib/vue.js' {
  declare module.exports: $Exports<'vuenit/lib/vue'>;
}
